version: '3'
services:
  eureka-server:
    image: "eureka-server"
    ports:
      - "8761:8761"
  zuul-gateway:
    image: "gateway"
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
  catalog-data:
    image: "catalog-data"
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
    ports:
      - "8100"
    depends_on:
      - eureka-server
  item-catalog:
    image: "item-catalog"
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
    ports:
      - "8000"
    depends_on:
      - eureka-server

networks:
    my-network:
        driver: bridge